services:
  database:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: cashFlow
    volumes:
      - mongo_data:/data/db

  transaction:
    image: cashflow.transaction:latest
    build:
      context: ../../..
      dockerfile: Deployment/Local/DockerFiles/DockerfileTransaction
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - database

  consolidation:
    image: cashflow.consolidation:latest
    build:
      context: ../../..
      dockerfile: Deployment/Local/DockerFiles/DockerfileConsolidation
    ports:
      - "8081:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - database
volumes:
  mongo_data:
